FROM node:22-alpine

WORKDIR /app

COPY . .

COPY package*.json ./

RUN npm install && npm cache clean --force

# CMD npx prisma generate && npx prisma migrate deploy && npm run start:dev
CMD npx prisma generate && npx prisma migrate deploy